# Generated by Django 6.0.3 on 2026-03-18 11:07

import residences.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(default=residences.models.generate_uniqueId, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('road_number', models.CharField(max_length=50, null=True)),
                ('floor', models.IntegerField(null=True)),
                ('flat_number', models.CharField(max_length=50, null=True)),
                ('square_meters', models.DecimalField(decimal_places=2, max_digits=6)),
                ('energy_class', models.CharField(max_length=10, null=True)),
                ('power_supply_number', models.CharField(max_length=50, null=True)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('latitude', models.CharField(max_length=200, null=True)),
                ('longitude', models.CharField(max_length=200, null=True)),
                ('construction_year', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'residences',
            },
        ),
        migrations.CreateModel(
            name='ResidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'residence_files',
            },
        ),
        migrations.CreateModel(
            name='ResidenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'residence_types',
            },
        ),
    ]
