# Generated by Django 5.1.4 on 2026-06-17 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residencefile',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residences.residence'),
        ),
        migrations.AddField(
            model_name='residence',
            name='residenceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residences.residencetype'),
        ),
    ]
