import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import "./globals.css"
import 'primeicons/primeicons.css'
import "primereact/resources/themes/lara-light-cyan/theme.css"

import 'primeflex/primeflex.css'

import 'leaflet/dist/leaflet.css';


import { PrimeReactProvider } from 'primereact/api'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" /> */}
        {/* <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossOrigin="anonymous" /> */}
      </head>
      {/* <Script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" ></Script> */}

      <PrimeReactProvider>
        <body className="min-h-full flex flex-col">{children}</body>
      </PrimeReactProvider>
    </html>
  );
}
