# Generated by Django 6.0.3 on 2026-03-18 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'technician_types',
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_1', models.CharField(max_length=10, null=True)),
                ('phone_2', models.CharField(max_length=10, null=True)),
                ('technicianType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technicians.techniciantype')),
            ],
            options={
                'db_table': 'technicians',
            },
        ),
    ]
