# Generated by Django 6.0.3 on 2026-03-18 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenances', '0001_initial'),
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residences.residence'),
        ),
        migrations.AddField(
            model_name='maintenancehistory',
            name='maintenanceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenances.maintenance'),
        ),
    ]
