# Generated by Django 5.1.4 on 2026-08-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('organization', models.CharField(blank=True, max_length=300, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('announcement_url', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gov_announcements',
                'ordering': ['-published_at'],
            },
        ),
    ]
